### ISSUE TITLE
Unable to compile TypeScript when import reflect-metadata

### ISSUE THREAD

**Issue by dews** [rbuckton/reflect-metadata#118]
I have a script,
```
import 'reflect-metadata'

const plane = {
  color: 'red'
}

Reflect.defineMetadata('note', 'hi there', plane)
```
I set tsconfig.json,
```
/* Experimental Options */
"experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
"emitDecoratorMetadata": true, 
```
And run `npm install reflect-metadata`

Use `ts-node` to run run it but got an error,
```
# ts-node demo.ts
/usr/local/lib/node_modules/ts-node/src/index.ts:293
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
test.ts:7:9 - error TS2339: Property 'defineMetadata' does not exist on type 'typeof Reflect'.

7 Reflect.defineMetadata('note', 'hi there', plane)
          ~~~~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:293:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:297:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:399:34)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:457:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:536:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
```

But I can use `tsc demo.ts` to build a demo.js and run it without an error.

**Comment by dews** [comment]
I found the issue is from tsconfig.json, the `module` should be `commonjs` or just comment out.
```
{
  "compilerOptions": {
    /* Basic Options */
    // "incremental": true,      /* Enable incremental compilation */
    "target": "ES2019",          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "commonjs",        /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
  }
}
```
Althoudth I still don't understad the root cuase. The `tsc demo.ts` can pass with any module options but `ts-node demo.ts` can't

**Comment by ljharb** [comment]
Running with tsc ignores your local config by default (unlike every other similar tool)
