### ISSUE TITLE
Infinite loop in v0.2.0

### ISSUE THREAD

**Issue by alumni** [rbuckton/reflect-metadata#153]
```
    RangeError: Maximum call stack size exceeded
      at IsUndefined (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:673:13)
      at getProviderNoCache (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:919:22)
      at Object.getProvider (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:955:28)
      at GetMetadataProvider (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:1157:55)
      at OrdinaryOwnMetadataKeys (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:649:28)
      at Reflect.getOwnMetadataKeys (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:494:20)
      at Object.isProviderFor (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:1134:33)
      at getProviderNoCache (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:941:56)
      at Object.getProvider (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:955:28)
      at GetMetadataProvider (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:1157:55)
      at OrdinaryOwnMetadataKeys (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:649:28)
      at Reflect.getOwnMetadataKeys (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:494:20)
      at Object.isProviderFor (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:1134:33)
      at getProviderNoCache (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:941:56)
      at Object.getProvider (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:955:28)
      at GetMetadataProvider (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:1157:55)
      at OrdinaryOwnMetadataKeys (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:649:28)
      at Reflect.getOwnMetadataKeys (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:494:20)
      at Object.isProviderFor (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:1134:33)
      at getProviderNoCache (../../node_modules/.pnpm/reflect-metadata@0.2.0/node_modules/reflect-metadata/Reflect.js:941:56)
      ...
```

**Comment by rbuckton** [comment]
Thanks, I'm looking into it. Would you be able to provide a minimal repro? I didn't encounter this in testing and would like to isolate what's causing it.

**Comment by rbuckton** [comment]
Disregard, I was able to reproduce the error.
