### ISSUE TITLE
Package subpath './Reflect' is not defined by "exports"

### ISSUE THREAD

**Issue by yadickson** [rbuckton/reflect-metadata#154]
Hello,

With

node 16.20.2
npm 8.19.4
reflect-metadata 0.2.0
mocha 8.4.0
mocha-junit-reporter 2.2.1
mocha-multi-reporters 1.5.1

When run mocha with reflect-metadata v0.2.0, show the next error

`
npm t                   

> APP@1.0.0 test
> mocha --reporter mocha-multi-reporters --reporter-options configFile=.mocharc.json

✖ ERROR: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './Reflect' is not defined by "exports" in APP/node_modules/reflect-metadata/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
    at resolveExports (node:internal/modules/cjs/loader:584:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:658:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (APP/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._resolveFilename (APP/node_modules/tsconfig-paths/src/register.ts:90:36)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at exports.requireOrImport (APP/node_modules/mocha/lib/esm-utils.js:42:12)
    at exports.handleRequires (APP/node_modules/mocha/lib/cli/run-helpers.js:94:34)
    at async APP/node_modules/mocha/lib/cli/run.js:341:25 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
`

`
.mocharc

{
    "$schema": "https://json.schemastore.org/mocharc",
    "exit": true,
    "extension": [".ts"],
    "reporter": "spec",
    "reporterEnabled": "spec, mocha-junit-reporter",
    "mochaJunitReporterReporterOptions": {
	    "mochaFile": "./reports/xunit.xml"
    },
    "timeout": 2000,
    "recursive": true,
    "spec": [ "test/**/*.spec.ts" ],
    "require": [ "ts-node/register", "source-map-support/register", "tsconfig-paths/register", "reflect-metadata/Reflect" ]
}
`

But with reflect-metadata v0.1.14, all is OK

Thanks for your time.

**Comment by rbuckton** [comment]
It was never intended that you should directly reach into the package except when loading via a `<script>` tag. Is just importing `reflect-metadata` an option?

**Comment by yadickson** [comment]
Hello,

I fixed the problem, 

I changed the .mocharc config file

`
.mocharc

{
"$schema": "https://json.schemastore.org/mocharc",
"exit": true,
"extension": [".ts"],
"reporter": "spec",
"reporterEnabled": "spec, mocha-junit-reporter",
"mochaJunitReporterReporterOptions": {
"mochaFile": "./reports/xunit.xml"
},
"timeout": 2000,
"recursive": true,
"spec": [ "test/**/*.spec.ts" ],
"require": [ "ts-node/register", "source-map-support/register", "tsconfig-paths/register", "reflect-metadata" ]
}
`

From reflect-metadata/Reflect to reflect-metadata

Thanks for your time... :)

**Comment by rbuckton** [comment]
#157 will add backwards-compatible subpath exports for anyone else that runs into this.
