### ISSUE TITLE
getMetadataKeys throw TypeError on IE

### ISSUE THREAD

**Issue by raeesaacapita** [rbuckton/reflect-metadata#69]
I am getting following error on calling getMetadataKeys on target object only on IE browser. Code works fine on chrome and firefox - 

```
TypeError
   at GetIterator (https://localhost:8787/public/reflect-metadata/reflect-metadata.js:821:13)
   at OrdinaryOwnMetadataKeys (https://localhost:8787/public/reflect-metadata/reflect-metadata.js:640:9)
   at OrdinaryMetadataKeys (https://localhost:8787/public/reflect-metadata/reflect-metadata.js:603:9)
   at OrdinaryMetadataKeys (https://localhost:8787/public/reflect-metadata/reflect-metadata.js:607:9)
   at getMetadataKeys (https://localhost:8787/public/reflect-metadata/reflect-metadata.js:417:9)
   at PropertiesValidator.recursivelyValidateObject (https://localhost:8787/public/validation/validator.js:34:13)
   at PropertiesValidator.validateEntity (https://localhost:8787/public/validation/validator.js:21:13)
   at Anonymous function (https://localhost:8787/public/Entity.js:18:17)
   at k (https://localhost:8787/public/rsvp/rsvp.min.js:1:2994)
   at Y (https://localhost:8787/public/rsvp/rsvp.min.js:1:4671)
```

We have used property decorator.

**Comment by raeesaacapita** [comment]
I am facing above issue in version 0.1.10, downgrading to version 0.1.8 worked fine.

**Comment by lucasheim** [comment]
+1

**Comment by henriale** [comment]
using [core-js](https://www.npmjs.com/package/core-js) worked for me
